# Generated by Django 5.0.6 on 2024-06-07 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, max_length=400)),
                ('background', models.ImageField(blank=True, null=True, upload_to='images/backgrounds')),
                ('is_active', models.BooleanField(default=True, verbose_name='active / not active')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phrase',
                'verbose_name_plural': 'phrases',
            },
        ),
    ]
