# Generated by Django 5.0.6 on 2024-06-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='slug',
        ),
    ]
